'use strict';

// The text tables of people.js, moved out so the logic reads on its own (#254). Data only; loaded before people.js.

const NAMES = {
  earth: {
    first: [
      'Amara',
      'Daniel',
      'Priya',
      'Mateo',
      'Chen',
      'Fatima',
      'Oliver',
      'Aiko',
      'Samuel',
      'Leila',
      'Tomas',
      'Grace',
      'Ravi',
      'Ines',
      'Kwame',
      'Hana',
      'Diego',
      'Nadia',
      'Arjun',
      'Sofia'
    ],
    last: [
      'Nakamura',
      'Silva',
      'Hassan',
      'Kowalski',
      'Mbeki',
      'Singh',
      'Ferreira',
      'Lindqvist',
      'Moreau',
      'Castillo',
      'Haddad',
      'Petrov',
      'Osei',
      'Tanaka',
      'Mendoza',
      'Kaur',
      'Novak',
      'Achebe',
      'Okonjo',
      'Brennan'
    ],
    jobs: [
      'accountant',
      'schoolteacher',
      'insurance adjuster',
      'journalist',
      'nurse',
      'software auditor',
      'lawyer',
      'aid worker',
      'sales rep'
    ]
  },
  mars: {
    first: [
      'Marcus',
      'Yelena',
      'Tariq',
      'Ingrid',
      'Hector',
      'Mei',
      'Anton',
      'Zara',
      'Felix',
      'Olga',
      'Kenji',
      'Dalia',
      'Viktor',
      'Sana',
      'Ruben',
      'Noor'
    ],
    last: [
      'Holloway',
      'Achterberg',
      'Castellanos',
      'Ibarra',
      'Kerr',
      'Laszlo',
      'Quint',
      'Reyes',
      'Sato',
      'Ueda',
      'Valenti',
      'Weller',
      'Zamora',
      'Okoye',
      'Brandvold'
    ],
    jobs: [
      'terraforming engineer',
      'soil chemist',
      'dome architect',
      'navy veteran',
      'hydrologist',
      'teacher',
      'atmospheric modeler'
    ]
  },
  belt: {
    first: [
      'Tiko',
      'Ama',
      'Bexa',
      'Dru',
      'Esa',
      'Fen',
      'Gaz',
      'Imi',
      'Jo',
      'Kez',
      'Lolo',
      'Mika',
      'Nim',
      'Pax',
      'Ruo',
      'Sabe',
      'Tuk',
      'Vesna',
      'Wim',
      'Yuri'
    ],
    last: [
      'Ashford-Kamau',
      'Bello',
      'Chu-Okoro',
      'Dagny',
      'Esteban-Li',
      'Faro',
      'Ghosh',
      'Hollis',
      'Iwu',
      'Jansen-Ruiz',
      'Kalu',
      'Lindo',
      'Marsh',
      'Nyambura',
      'Oyelaran',
      'Pike',
      'Quesada',
      'Rourke',
      'Soto-Nakamura',
      'Tembo'
    ],
    jobs: [
      'ice miner',
      'hydroponics tech',
      'dockworker',
      'refinery welder',
      'water recycler tech',
      'salvager',
      'ore assayer',
      'EVA rigger'
    ]
  }
};

const TRAITS = {
  talkative: {
    adj: 'talkative',
    chatter: [
      '{first}: "Did I ever tell you about the time on {home}..."',
      '{first} is telling a long story in the galley, and, from the sound of it, has reached the good part for the third time.',
      '{first}: "And that, I always say, is the whole trouble with {home}. Oh, but that reminds me..."',
      '{first} has been talking for an hour, and the coffee maker, in a corner, has given up in sympathy.',
      '{first} is explaining, to nobody in particular, what they would do with a ship of their own.'
    ]
  },
  nervous: {
    adj: 'nervous',
    chatter: [
      '{first} keeps checking the hull pressure readouts.',
      '{first} jumps at a clank from the engine room, and pretends they did not.',
      '{first} has, for the fifth time this watch, tested the seal on the nearest hatch.',
      '{first} is counting the emergency suits, quietly, under their breath, in a low, steady mutter.',
      '{first} sleeps with a hand on the bulkhead.'
    ]
  },
  generous: {
    adj: 'generous',
    chatter: [
      '{first} made coffee for everyone.',
      '{first} has left a plate of something sweet outside the engine room, without a note.',
      '{first} is giving away, one piece at a time, the contents of their sock drawer.',
      '{first} covered someone\'s shift, and will not hear a word about it.',
      '{first} has a knack for turning up, unasked, with exactly what you need.'
    ]
  },
  greedy: {
    adj: 'money-minded',
    chatter: [
      '{first} is doing sums on a hand terminal and muttering.',
      '{first} has worked out what every ton of cargo on the ship is worth, and tells you, twice.',
      '{first} is running the numbers on a trade route, and, from the muttering, it is not going to be enough.',
      '{first} watches the fuel gauge, and does not blink.',
      '{first} has started a betting pool on the arrival date, and holds all the odds.'
    ]
  },
  pious: {
    adj: 'devout',
    chatter: [
      '{first} is praying quietly in the cargo bay.',
      '{first} has tied a ribbon to a bulkhead, for luck, and blessed it.',
      '{first} murmurs a short blessing over the drive before each flip.',
      '{first} is reading, aloud and softly, from a worn book.',
      '{first} is lighting a very small, very safe candle in a jar, and shielding it from the draught with a hand.'
    ]
  },
  rude: {
    adj: 'abrasive',
    chatter: [
      '{first}: "Who designed this galley, and were they drunk?"',
      '{first} is complaining about the coffee. The coffee, to be fair, deserves it.',
      '{first}: "In my last ship, we had a proper bunk. With a door."',
      '{first} has an opinion about the way you are flying, and shares it, generously, at every turn.',
      '{first} is glaring at the thermostat.'
    ]
  },
  curious: {
    adj: 'curious',
    chatter: [
      '{first} is asking the nav computer far too many questions.',
      '{first} has taken the panel off the galley clock to see what makes it tick.',
      '{first} is following the plume readout with a notebook, and a look of pure joy.',
      '{first}: "But why does it hum at that particular note? Has anybody ever asked?"',
      '{first} is pressing an ear to the bulkhead, listening to something nobody else can hear.'
    ]
  },
  drunk: {
    adj: 'hard-drinking',
    chatter: [
      '{first} is suspiciously cheerful for this hour.',
      '{first} is humming, loudly, an old song from {home}, and has forgotten the second verse.',
      '{first} is sitting very carefully upright, with a mug that smells like anything but coffee.',
      '{first} has made a toast to the ship, and is now, tenderly, toasting the coffee maker.',
      '{first} is cheerfully explaining something to a coaster.'
    ]
  },
  secretive: {
    adj: 'guarded',
    chatter: [
      '{first} closes a message window whenever you walk past.',
      '{first} answers every question with a question, and does it very gracefully.',
      '{first} has a locked case, and a way of standing between it and everyone else.',
      '{first} is very quiet, and very watchful, and always knows where everyone is.',
      '{first} deletes a message, and looks up, and smiles at you.'
    ]
  },
  kind: {
    adj: 'kind',
    chatter: [
      '{first} fixed the squeaky hatch without being asked.',
      '{first} noticed someone was tired, and quietly took the rest of their watch.',
      '{first} is sewing a torn sleeve, by a lamp, for someone who is not going to ask.',
      '{first} has left a note on the galley wall: "Ask me if you need anything. Anything at all."',
      '{first} is humming, softly, at the sink, while washing everyone else\'s cups.'
    ]
  },
  brave: {
    adj: 'steady',
    chatter: [
      '{first} volunteered for the next EVA before anyone asked.',
      '{first} is calmly checking the emergency hatches, one by one, whistling.',
      '{first} has a plain scar, and a plain refusal to talk about it.',
      '{first}: "If anything goes wrong, I will be the one to go and look. That is what I am for."',
      '{first} is smiling, in the face of a very small, very real problem with the coolant.'
    ]
  },
  homesick: {
    adj: 'homesick',
    chatter: [
      '{first} is looking through old pictures of {home}.',
      '{first} has gone very quiet, and is watching the viewport.',
      '{first} is making a dish from {home}, out of not-quite-right ingredients, and eating it with great seriousness.',
      '{first} is humming something from {home}, low and soft, and does not seem to know.',
      '{first} keeps a stone from {home}, worn smooth, and turns it over, and over, and over.'
    ]
  }
};

const SHIP_WORDS = {
  a: [
    'Patient',
    'Lucky',
    'Stubborn',
    'Quiet',
    'Wandering',
    'Iron',
    'Honest',
    'Restless',
    'Silver',
    'Distant',
    'Second',
    'Brave'
  ],
  n: [
    'Promise',
    'Horizon',
    'Tortoise',
    'Heron',
    'Bargain',
    'Anvil',
    'Lantern',
    'Wager',
    'Pilgrim',
    'Ember',
    'Mule',
    'Comet'
  ],
  pa: ['Crimson', 'Hungry', 'Silent', 'Black', 'Bitter', 'Rusted'],
  pn: ['Knife', 'Grin', 'Debt', 'Tooth', 'Widow', 'Vulture', 'Hook']
};

// The words of the passenger events (PAX_EVENTS) and the crew events (CREW_EVENTS) of js/people.js (#457), by the id of each event and the name each line has: `title`, `text`, and for each choice `c0.label` and
// its result (`c0.result`, or `c0.win` and `c0.lose` where the choice rolls). A {word} is filled from the game when the event plays: {first}, {last}, {home} and {crime} are
// the passenger's, {dest} the port they are bound for, {armor} the hull the event takes and {rumor} the tip it gives; {crew} is the shipmate who does the work, and the dialog fills it. A crew event's {first}, {last} and {home} are the shipmate's, and {raise} the new wage. The bar topics' lines (`bar:<topic>`, js/bartopics.js) have {first}, {home} and the like, and the words the topic builds: {rumor} (a tip), {react} (how they took it), {slip} (what a secret lets slip), {cr} and {cost} (the stake).
// What a choice does (credits, regard, time, who stays aboard) is in code. tests/peoplelines.test.js plays every event and checks that each name here is read.
const PEOPLE_LINES = {
  'people:pax:contraband': {
    title: 'Customs Inspection',
    text: 'The customs cutter\'s searchlight comes across the hull plate by plate. "Ship, this is Inspection," says the voice on the open band. "Hold your burn and open the hold to a scan. It takes a quarter hour, and we do it twice if there is a reason to." {first} is at the hold hatch with one hand on the frame. "Captain." {first} says it low. "Whatever you can do. Stall them. I will explain at the next port, and you will not like it, but I will explain."',
    'c0.label': 'Stall them',
    'c0.win': '"Inspection, the hold scanner has a fault," you say, and then you have the fault\'s maintenance log, and three forms in the wrong order that she has to send back. "That is your problem, captain," the officer says. "It will be mine when I log it," you say. It takes forty-one minutes. Her intercept window closes at forty-two, and the cutter peels away with a burst of static. {first} sits down on a crate. At the airlock {first} puts a folded note in your hand and does not say what it is for.',
    'c0.lose': '"That is the second form I have asked for," the officer says. "For the third I come aboard." She comes aboard. They find {first}\'s stash behind a false panel in the second bay, in under ten minutes. "Negligent inspection," she says, writing it, "two thousand credits." You pay it. At supper the only sound in the galley is cutlery.',
    'c1.label': '[{crew}] Spoof the cargo manifest',
    'c1.win': '{crew} sits down at the console. "Ninety seconds," {crew} says, "and do not talk to me." In ninety seconds the manifest, the cargo record and the ship\'s last six ports are rewritten. The scan crosses the hold and reads tidy crates and honest paperwork. {first} watches from the hatch, looks at you, and then at {crew}.',
    'c1.lose': '{crew}\'s spoof fails a checksum on one line of the manifest, and the scanner lights. You pay a 2,000 cr fine. "One digit," {crew} says, for the next hour. "It was one digit."',
    'c2.label': 'Turn {first} in (+1,500 cr reward)',
    'c2.result': '"{first} {last}," the officer says, once, to be sure, and customs takes {first} off in cuffs with one hand on their shoulder. {first} does not look back. The airlock cycles. At the galley table a cup is left half full, and nobody clears it.',
  },
  'people:pax:wanted': {
    title: 'Bounty Hunter',
    text: 'A bounty hunter matches your burn, dark, with one running light that winks on and off. "You are carrying {first} {last}," says the voice on the channel, low and unhurried. "Wanted on {home} for {crime}. Five thousand for the handover. Or I come and take them, and that costs everyone aboard." In the galley {first} sets a cup on the table and turns it a quarter turn, so that the handle faces away.',
    'c0.label': 'Hand them over (+5,000 cr)',
    'c0.result': '"Dock at my lock," the hunter says, "and keep your hands off the panel." {first} goes across with one bag. At the lock {first} looks back once. The credits arrive before the lock finishes cycling.',
    'c1.label': '[{crew}] Make them reconsider',
    'c1.result': '{crew} puts a burst of tracer across the hunter\'s bow, a line of light that picks out the hull number. "That was the warning," {crew} says on the channel. "The next one has a number on it." The hunter reconsiders. One wild shot comes back and costs you {armor} points of armor. At the airlock {first} pays you extra and shakes your hand hard enough to hurt.',
    'c2.label': 'Refuse, and fight if you must',
    'c2.win': 'It takes a long, ugly exchange to drive the hunter off, and it costs you {armor} points of armor and an antenna. That night in the galley, over a bulb of something strong, {first} tells you their side of it. "A bad partner and a worse lawyer," {first} says, "and I did not do half of what is on the sheet." The bulb is empty before the other half.',
    'c2.lose': 'The hunter hammers the hull for three minutes, {armor} points of armor, and then breaks off with a curse on the channel. {first}, gray in the face, holds the patch plate. "Hold it flat," you say, and {first} does, while you seal the worst of the breaches.',
  },
  'people:pax:ill': {
    title: 'Medical Emergency',
    text: '{first} goes down in the galley, dropping a cup, and slides to the deck with their back against a cabinet. Their breathing is shallow and fast. {reason} Everyone in the room has stopped moving. They look at you.',
    'reason.ill': 'Between breaths they say they have hidden an illness for weeks and did not want to be a burden.',
    'reason.medical': 'The condition they were traveling to get treated has taken a turn.',
    'c0.label': '[{crew}] Treat them',
    'c0.result': '{crew} works through the night with a lamp and a case of instruments and does not leave the bunk. By morning {first} is sitting up, pale, asking for coffee in a cracked voice. {crew} is asleep in the corridor with a blanket over their shoulders, and nobody steps over them.',
    'c1.label': 'Use the ship\'s medkit (500 cr of supplies)',
    'c1.win': 'You sit up with them through the night, working from the manual, with a bulb of water and a flashlight in your teeth. The fever breaks in the small hours, and they sleep for the first time in days.',
    'c1.lose': 'You do everything the medkit and the manual allow, and it holds them stable. They need a real doctor. For the rest of the burn you take their pulse every twenty minutes, in the dark.',
    'c2.label': 'Burn harder to get them help (40 reaction mass)',
    'c2.result': 'You push the drive until the frame ticks. {first} lies pinned to a bunk with a wet cloth on their forehead and asks, every hour, how many hours you have saved. When the doctors take them at the dock, they say something you do not catch. It might be thanks.',
    'c3.label': 'There is nothing you can do',
    'c3.result': '{first} recovers over three days, on their own, in a cold bunk. They ask you for nothing, and they do not speak to you for the rest of the trip. At the dock they go down the ramp without turning round.',
  },
  'people:pax:spy': {
    title: 'Encrypted Bursts',
    text: 'Your comms log shows {first} sending tight-beam bursts between the second and third watch, short pulses aimed at no port you know. They send them from the observation blister, alone, with the lights off. You have started to count how many times a shift {first} looks at the door.',
    'c0.label': 'Confront them',
    'c0.win': '{first} sighs, looks at you, and transfers 2,500 cr "for your discretion". "I like you, captain," they say. "I would rather not have to like you less."',
    'c0.lose': '{first} tells you, evenly, that it is none of your business. They do not raise their voice and they do not threaten you. They stand there until you leave.',
    'c1.label': '[{crew}] Quietly decrypt the traffic',
    'c1.result': '{crew} cracks it over a long evening. Someone is paying for market numbers from every port you touch, in tidy weekly reports. Nothing dangerous: a patient stranger who wants to know what everything costs. Among the bursts is one line you can use: "{rumor}"',
    'c2.label': 'Not your business',
    'c2.result': 'You let it go. The bursts keep coming every night at the same hour. Once, in the corridor, {first} meets your eye and keeps walking.',
  },
  'people:pax:debt': {
    title: 'Collectors',
    text: 'A collection agency hails and reads from a script: {first} owes 1,500 credits and they want it now, "or we flag your ship as an accessory". In the corner of the galley {first} has gone the color of old paper and is looking at the deck. The agent adds, pleasantly, that they have "a great deal of patience, and a great many lawyers."',
    'c0.label': 'Pay it for them (1,500 cr)',
    'c0.result': '{first} opens their mouth and nothing comes out. Then they say, low, that they will pay you back with interest, every credit, if it takes the rest of their life. They do not sit down until you have.',
    'c1.label': 'Tell the collectors to get lost',
    'c1.result': 'They threaten legal action at length and cut the channel. Nothing comes of it. {first} looks at you across the galley. Later there is a cup of tea at your elbow that you did not ask for.',
  },
  'people:pax:job': {
    title: 'Running Late',
    text: '{first} has a job interview on {dest}, and the schedule is tighter than they thought. They have ironed their good shirt three times in the galley and run their answers at the mirror. Now they stand at the cockpit hatch, twisting their hands. "Captain, I hate to ask. Is there any way to go faster?"',
    'c0.label': '[{crew}] Find a faster line',
    'c0.result': '{crew} bends over the nav display, muttering, and finds a gravity assist nobody else would try, a long swoop round a moon that barely shows on the charts. It works. {first} arrives with an hour to spare, freshly ironed, and at the dock hugs {crew} before {crew} can step back.',
    'c1.label': 'Hard burn (40 reaction mass)',
    'c1.result': 'You push the drive, and {first} spends the burn on a crash couch, running answers through their teeth. They arrive on time, rumpled and out of breath, with no time to thank you. You watch them run for the concourse, straightening their collar.',
    'c2.label': '"Physics does not negotiate."',
    'c2.result': 'They say all right and go back to their bunk. For the rest of the trip you can hear them through the bulkhead, running their answers again and again. You never learn whether they made the interview.',
  },
  'people:pax:research': {
    title: 'Sample Opportunity',
    text: '{first} has been at the observation blister for hours with a battered notebook and a pair of binoculars. Now they appear at the cockpit hatch, out of breath, hair on end. They have spotted a rock a few hours off your trajectory, pale, with a bright glint in the sun. "A sample from that could make my career," they say. "I will pay for the detour. Please. I have waited my whole life for something like this."',
    'c0.label': 'Match orbits and take a sample (costs time)',
    'c0.result': '{first} spends six hours in a vac suit on the rock, tethered to your hull, giggling into the radio and chipping at the crust with a tiny hammer. When they come back in, frosted and shaking, they hold a vial up to the light. They promise to name something after you.',
    'c1.label': 'Stay on course',
    'c1.result': 'They watch it slide past the window, a pale point in the dark, and stay at the glass until it is gone. Later you see them write something in the notebook: the date, and a line you cannot read. They are polite for the rest of the trip. When they disembark they leave a folded drawing on the galley table, of a rock, and a ship, and a long distance.',
  },
  'people:pax:pilgrim': {
    title: 'A Request for Stillness',
    text: '{first} comes to the cockpit hatch holding a worn book. They ask whether you might cut the drive for a few hours, so that they can hold a prayer service in zero g. It is a holy day for them, and the old prayers say that in weightlessness a person is closest to whatever is out there. They do not press. They wait with their hands folded, and the book shakes in their grip.',
    'c0.label': 'Cut thrust for them (costs time)',
    'c0.result': 'The drive falls silent. They drift through the cargo bay in a slow circle, singing in a language older than any port, and one by one other passengers and crew drift in to listen. When it is over they press a donation on you, in small folded notes, and touch the bulkhead once.',
    'c1.label': 'Decline politely',
    'c1.result': 'They thank you for hearing them. They pray at one g instead, kneeling on the cold deck of the cargo bay.',
  },
  'people:pax:talkative': {
    title: 'Long Stories',
    text: '{first} corners you in the galley with a bulb of coffee and begins to talk before you can leave. They talk about {home}: the streets, the smells, the bakery at the corner, the neighbor who kept bees, the long evenings. Every story is longer than the last, and every one ends with "and then, of course, I left."',
    'c0.label': 'Listen',
    'c0.result': 'You listen for an hour, and then another. Near the end, between the bakery and the bees, is something you can use: "{rumor}" {first} gives you a shy smile.',
    'c1.label': 'Excuse yourself to the cockpit',
    'c1.result': 'You escape to the cockpit with a muttered excuse and check the instruments. {first} finds someone else to talk to. Through the hatch, for the next hour, you hear the stories moving from bunk to bunk.',
  },
  'people:pax:nervous': {
    title: 'Panic at the Flip',
    text: '{first} panics when the drive cuts for the flip. The silence and the sudden lightness come at once, and they are sure the reactor has failed. They grip the edge of the bunk, breathing in short gasps, and a low moan starts in their throat. The others look at you.',
    'c0.label': 'Talk them through it',
    'c0.result': 'You sit beside them and explain flip-and-burn three times, slowly, with a hand on their shoulder and a cup of water. The third time you draw it on the bulkhead with a finger. The trembling slows, and they laugh once, wetly. {first} apologizes. You tell them there is nothing to apologize for.',
    'c1.label': 'Give them a sedative (200 cr)',
    'c1.result': '{first} takes the sedative with a shaking hand and lies back on the bunk. Within minutes they are breathing slow. They sleep through the rest of the burn and wake at the dock with no memory of what frightened them.',
    'c2.label': 'Tell them to pull themselves together',
    'c2.result': '{first} flinches and goes quiet. They spend the rest of the trip in their bunk with the curtain drawn, eating little, speaking to no one. Sometimes, in the night, you can hear them.',
  },
  'people:pax:curious': {
    title: 'Engine Room Tour',
    text: '{first} has been hovering near the engine room hatch for two days, with an ear pressed to the bulkhead. Now they come to you. "Captain, I would love to see the drive room. Just a quick look. I will not touch anything. I promise. I have always wanted to know how it works."',
    'c0.label': 'Show them around',
    'c0.spill': '{first} touches something. A hiss goes up, and a valve you did not know existed blows its seal. You vent 20 units of reaction mass into the black before you can shut it. {first} apologizes for the next hour, fast and stammering, until you laugh.',
    'c0.fine': '{first} asks questions for an hour, about coolant loops and injector timing and why the drive hums at that note. You find yourself explaining, and enjoying it. By the end you are both leaning on a pipe with the drive humming around you.',
    'c1.label': 'Crew only, sorry',
    'c1.result': 'They say they understand and are sorry to have asked. That evening you find them at the observation blister with an ear against the wall, listening to the drive. When they see you, they go on listening.',
  },
  'people:pax:drunk': {
    title: 'Galley Incident',
    text: '{first} got into the good whiskey, the bottle you were saving, and somewhere around the third glass decided to give the galley water recycler "a bit of a fix", with a spoon and a fork. There is a gap in the wall and a fine mist in the air. {first} is sitting in the middle of the galley, wet through, holding the spoon upright. Repairs will run about 400 credits.',
    'c0.label': 'Add it to their fare',
    'c0.result': '{first} grumbles, studies the deck, and says "unreasonable" to nobody. They stay out of the galley for the rest of the trip, and at the dock they pay in full, in small folded notes.',
    'c1.label': 'Let it slide (400 cr)',
    'c1.result': '{first} goes deep red. They clean the galley themselves, top to bottom, all night, with a toothbrush, and in the morning it is the cleanest room on the ship. There is a note on the door in pencil: "Sorry. Thank you. Never again."',
  },
  'people:pax:greedy': {
    title: 'Card Game',
    text: '{first} produces a deck worn soft at the corners and shuffles it with a flourish. "A friendly game, captain," {first} says. "With a little money on it, just to make things interesting. It is a long burn, and a man gets bored." The deck is not yet square, and {first} is already smiling.',
    'c0.label': 'Play (500 cr stake)',
    'c0.win': 'You clean {first} out in one long quiet hand. {first} looks at the table for ten seconds. "Luck," {first} says. For the rest of the trip {first} sits in a corner and mutters it at the deck.',
    'c0.lose': '{first} wins in one slow hand, turning a single card over at the end. "Well," {first} says, and gathers the money. "That was friendly." For the rest of the trip {first} hums in the corridors and shuffles the deck where you can see it.',
    'c1.label': 'Decline',
    'c1.result': '"Suit yourself," {first} says, and deals a hand of solitaire, slowly. You hear each card click down. {first} plays it out, loses, and begins again.',
  },
  'people:pax:generous': {
    title: 'Gratitude',
    text: '{first} takes over the galley for an afternoon and cooks a dinner for everyone aboard, with spices they brought from {home}, wrapped in twists of paper in a hidden pouch. The ship fills with the smell of cumin and roasted peppers, and the crew drift in one by one. At the end they insist on tipping you for a smooth trip, pressing the notes into your palm.',
    'c0.label': 'Accept graciously',
    'c0.result': 'You take the notes, and sit at the long table with the crew, elbow to elbow, passing dishes. It is the best meal the ship has had in months, and for an hour nobody talks about anything else. Somebody starts to sing, and the table joins in.',
    'c1.label': 'Refuse the money, keep the dinner',
    'c1.result': '{first} cannot speak for a moment. They take your hand in both of theirs, and then they write out the recipe on a napkin, every step, with a sketch of the pot. You will cook it, badly, for years.',
  },
  'people:pax:rude': {
    title: 'Complaints',
    text: '{first} has a list in a neat notebook, and reads it to you at the cockpit hatch, in order. "The bunk is too hard. The food is a crime. The gravity is insufficiently serious. The coffee tastes of pipe." {first} turns a page. "And frankly, captain, your face is not one I would choose to look at for so long."',
    'c0.label': 'Humor them',
    'c0.result': '"Item one," you say, and write it in a book. "The bunk." {first} reads the list again, slower, so that you can keep up. By the end of the hour {first} has run out. "Is there any more tea?" {first} asks.',
    'c1.label': 'Put them in their place',
    'c1.result': '"I have read your list," you say, in a level voice, "and here is what I think of it." You go item by item: the bunk is the bunk you were given, the food is the food you eat, and the gravity is the only gravity the drive makes. {first} goes pale, then red, then still. A formal complaint arrives that evening, in triplicate, and the fee comes out of your fare. The rest of the trip is quiet, and at night you can hear the drive again.',
  },
  'people:crew:greedy': {
    title: '{first} Wants a Raise',
    text: '{first} finds you at the end of a long shift with a printed sheet and folded arms. The sheet lists what crew with their skills earn on other ships, what a ship of your size can afford, and what {first} has done for you lately. The last line says: "I am worth it."',
    'c0.label': 'Give them 25% more ({raise} cr/day)',
    'c0.result': '{first} hums through the rest of the week and calls you "boss". Unasked, they tidy the corner of the cockpit.',
    'c1.label': 'No',
    'c1.result': '{first} goes back to work. For the next few days they do exactly what is asked and nothing more, and their tools are always where they were left. They have stopped smiling.',
  },
  'people:crew:drunk': {
    title: 'Galley Brawl',
    text: '{first} got drunk on something they had been keeping in a pipe, and had an argument with the galley bulkhead. The bulkhead won. There is a dent the size of a fist in the wall, blood on the deck, and {first} on the floor with a cloth pressed to their forehead. The medical supplies cost 300 cr.',
    'c0.label': 'Dock their pay',
    'c0.result': '{first} spends the week in a corner of the engine room with their back to the ship, and does the work in silence.',
    'c1.label': 'Pay for it and let it go (300 cr)',
    'c1.result': '{first} stares at the floor, then swears off drink. For now. They take the next three galley shifts. You find them scrubbing the bulkhead, and they do not look up. The dent is polished.',
  },
  'people:crew:homesick': {
    title: 'Homesick',
    text: '{first} has been quiet for days. At mealtimes they push their food around. At night you have seen them at the viewport, looking at a point of light. They have not said they miss {home}.',
    'c0.label': 'Give them a 500 cr bonus to call home',
    'c0.result': '{first} takes an hour on a lagged call home, in a quiet corner of the ship, with a hand over their mouth. They come back with red eyes and laugh once. They do not say what was said. For the rest of the week they hum in the corridors, and nobody mentions it.',
    'c1.label': 'Share a drink and listen',
    'c1.result': 'You pour two cups of something strong and sit on a crate beside them. For an hour they talk about {home}: the weather, the food, the quiet places. You say almost nothing. When they go to bed, they put a hand on your shoulder on the way out.',
    'c2.label': '"We all miss somewhere."',
    'c2.result': '{first} goes back to work. That night you see them at the viewport again, alone, and you leave them to it.',
  },
  'people:crew:nervous': {
    title: 'Bad Dreams',
    text: '{first} has not been sleeping. There are shadows under their eyes, they drop small tools, and they jump at every clank of the hull. When you ask, they tell you in a flat voice: nightmares about hull breaches, the same one every night. The thin bright line of a crack, spreading. The sudden silence. The cold.',
    'c0.label': 'Talk them through it',
    'c0.result': 'You sit with them in the galley at three in the morning with a pot of tea between you, and talk about nothing in particular. {first} sleeps through the night for the first time in a week. In the morning they bring you a cup of coffee and spill half of it.',
    'c1.label': 'Tell them to toughen up',
    'c1.result': '{first} flinches, and stops mentioning it. In the days after, the shadows under their eyes get darker. They check the seals on every hatch they pass.',
  },
  'people:crew:talkative': {
    title: 'Gossip',
    text: '{first} has been on the open band with half the ships in comm range, chatting. They know the name of the freighter captain\'s dog. They know who is feuding with whom at the next port. They lean in at your cabin door with news.',
    'c0.label': 'What have you heard?',
    'c0.result': '{first} sits down and gives you an hour of gossip: names, debts, who left whom at which port. In the middle of it is one thing you can use: "{rumor}" Then {first} moves on to the next thing.',
  },
  'people:crew:secretive': {
    title: 'Locked Locker',
    text: '{first}\'s locker has two locks, one you do not recognize and a cheap padlock over it. They have been receiving messages with no sender ID, short ones, at odd hours. They read them, delete them, and read them again. When you come into the room, they flinch.',
    'c0.label': 'Ask about it',
    'c0.result': '{first} looks at you. "Family business," {first} says. That is all you get. Afterward {first} takes meals in the bunk and locks the door to sleep.',
    'c1.label': 'Respect their privacy',
    'c1.result': 'You say nothing and turn to go. Behind you their shoulders come down. That evening {first} brings you a cup of tea you did not ask for, stands in the doorway, and goes.',
  },
  'people:crew:curious': {
    title: 'Tinkering',
    text: '{first} has the reaction mass pumps in pieces on newspaper in the middle of the engine room, "to see how they work". Every bolt is in a row. Three manuals are open, and there is a cup of cold tea. Nobody asked them to.',
    'c0.label': 'Let them experiment',
    'c0.win': 'They find a leak nobody knew about, a hairline crack in an old fitting that has been weeping mass for months, and seal it with a strip of foil. You recover 25 units of reaction mass. From then on the pumps run quiet, and {first} hums while they work.',
    'c0.lose': 'Something goes pop. A thin jet of reaction mass hisses out of the open housing before you can shut it, and you lose 20 units. {first} looks at the empty housing. "Ah," {first} says.',
    'c1.label': 'Put it back together. Now.',
    'c1.result': 'They reassemble every part, muttering, and the pumps run as before. {first} tightens the last bolt without looking at you.',
  },
  'people:crew:pious': {
    title: 'Quiet Prayer',
    text: '{first} finds you in the galley at the turn of the watch with a worn charm in one hand and asks you to join a short prayer for safe passage. They say it every burn, alone, in a corner, but tonight they wanted company. It will take a few minutes. They say you may stay silent.',
    'c0.label': 'Join them',
    'c0.result': 'You kneel beside them in the dim light. For a few minutes nobody speaks. The drive hums. A pipe ticks. When it ends, you both sit a moment. "Thank you," {first} says.',
    'c1.label': 'Politely decline',
    'c1.result': '{first} goes to their corner. Through the thin wall you hear the low murmur of their prayer. {first} prays for you anyway. You listen until it stops.',
  },
  'people:crew:rude': {
    title: 'Friction',
    text: '{first} has been needling the rest of the crew for days: a jab at breakfast, a remark in the corridor, a sneer at how someone hums. Tonight in the galley it is the humming again. A chair scrapes. "Say that again," says a level voice. "I said it was flat," {first} says. "I did not say it was your fault. I said it was flat." "Say that again." There is going to be a fight.',
    'c0.label': 'Reprimand them',
    'c0.result': 'You step between them. "Sit," you say. "Both of you." The room goes still. "You do not talk about a shipmate\'s humming at my table," you say to {first}, "or anywhere I can hear it." {first} goes red, then pale, and leaves. For days {first} eats alone.',
    'c1.label': 'Let them sort it out',
    'c1.result': 'You lean in the doorway with your arms folded and let them. It is short, loud and untidy, and involves a soup pot. {armor} points of hull damage later they are sitting side by side on the deck, breathing hard, sharing a cloth for a bloody lip. "It was flat," {first} says. "It was flat," says the other, and they both laugh.',
  },
  'people:crew:kind': {
    title: 'Small Kindnesses',
    text: '{first} spent the night fixing everyone\'s bunk lights, one by one, with a screwdriver, and in the small hours cooked a real meal from the last of the good stores. Nobody asked them to. In the morning every bunk had a light that worked, and every plate was full.',
    'c0.label': 'Thank them',
    'c0.result': 'You find {first} in the galley washing the last of the pots. You thank them. They wave it off and make a joke of it, and their ears go pink. For the rest of the trip nobody snaps at the table.',
  },
  'people:crew:generous': {
    title: 'Shared Bottle',
    text: '{first} comes into the galley at the end of a long shift with a dusty bottle wrapped in a shirt. They have carried it in the bottom of their bag since they left {home}. They set it on the table and take down every cup in the cupboard. "I was saving it for a special occasion," they say. "But I think we are the occasion."',
    'c0.label': 'Raise a glass',
    'c0.result': 'You raise a glass, and so does everyone else, in a ring around the table. The bottle tastes of {home}: sweet, smoky, with something bitter under it. To the ship. To the crew. To not dying. Somebody laughs, then everyone does, and the bottle goes round twice before it is empty.',
  },
  'people:crew:brave': {
    title: 'Volunteer',
    text: 'A sensor mast has come loose in the burn and hangs by one strut, banging against the hull with every pulse of the drive. It will tear free sooner or later and take plating with it. Before you can speak, {first} has the suit half on. "I will go, captain," they say, buckling a strap. "It is a ten-minute job. I have done worse."',
    'c0.label': 'Let them go',
    'c0.win': '{first} goes out through the lock with a tether and a bag of tools. For twenty minutes they are a bright shape against the stars, working along the hull. Then they are back inside, helmet off, sweating, grinning, holding the bent strut.',
    'c0.lose': 'A tether snaps. For one second {first} drifts, arms out, into the black, until a gloved hand catches a handhold and holds. They make it back, shaking and gasping. The ship takes {armor} points of damage from the loose mast, and nobody sleeps that night.',
    'c1.label': 'Go yourself',
    'c1.result': 'You go out through the lock yourself, with the tether at your belt, and fix it in the cold and the silence with the ship turning slowly below your boots. It takes forty minutes. {first} watched through the port, and when you come in {first} hands you a cup and says nothing.',
  },
  'bar:drink': {
    label: 'Buy {first} a drink ({cost} cr)',
    gate: 'You have bought them a drink already.',
    generous: '{first} will not hear of it, and slides the credits back across the bar, and buys the next one too. {react}',
    rumor: '{first} looks around and leans in. "Here\'s something you can use," they say, low and fast: "{rumor}" Then they sit back and finish their drink. {react}',
  },
  'bar:heard': {
    label: 'Ask what they have heard',
    gate: 'You have done that already tonight.',
    secretive: '"Nothing worth repeating," {first} says, and smiles. "And you? How long have you had the ship?"',
    heard: '{first} thinks about it, then says: "{rumor}"',
    more: '{first} adds, before you can answer: "{rumor}"',
  },
  'bar:passage': {
    label: 'Offer {first} passage',
    gate: 'You have offered already.',
    none: '{first} counts on their fingers, then shakes their head. "Nowhere you can reach from here," they say. "Ask me again when you have a longer tank."',
    set: '"{dest}?" {first} says. "That\'s where I need to be." They name a fare and shake on it with both hands. The job is on the mission board.',
  },
  'bar:cards': {
    label: 'Play {first} at cards ({cr} cr)',
    gate: 'You have played already tonight.',
    'win.rude': '{first} stands up and says, in a level voice, that you cheated, and the whole bar turns to look. You leave them to it.',
    'win.end.0': '{first} buys you a drink with your own money.',
    'win.end.1': '{first} shakes your hand and means it.',
    'win.end.2': '{first} tells the story of it to the next table, with you as the villain.',
    'lose.end': 'By the end of the glass you are laughing.',
  },
  'bar:work': {
    label: 'Ask {first} about their work',
    gate: 'You have done that already tonight.',
    post: 'You come away knowing something new about the {post}. (Experience gained.)',
    hands: 'Then {first} tells you what they are hearing on the docks: "{rumor}"',
  },
  'bar:place': {
    label: 'Ask {first} about this place',
    gate: 'You have done that already tonight.',
  },
  'bar:quiet': {
    label: 'Sit with {first} and say nothing',
    gate: 'You have done that already tonight.',
  },
  'bar:goal': {
    gate: 'You have done that already tonight.',
    result: 'You ask, and {first} puts down the glass.',
  },
  'bar:secret': {
    label: 'Ask {first} what is weighing on them',
    gate: 'You have done that already tonight.',
    result: '{first} looks at you, and takes their time deciding.',
  },
  'bar:home': {
    label: 'Ask about {home}',
    gate: 'You have done that already tonight.',
  },
  'bar:bless': {
    label: 'Ask for a blessing on your ship',
    'label.hired': 'Ask for a blessing on the ship',
    gate: 'You have done that already tonight.',
  },
  'bar:fight': {
    label: 'Tell them what you think of their manners',
    gate: 'You have done that already tonight.',
    win: 'It is short and loud. {step}{first} ends up on the floor, and the whole bar cheers. Someone starts a chant. The bartender charges you for the stool anyway.',
    'win.step': '{gunner} steps in and',
    lose: 'It is short, and it does not go your way. There is a light, and a loud noise, and then nothing. You wake up in the back with a black eye and a 150 cr bill for the mirror. The bartender is standing over you with a wet cloth. "You were doing so well," the bartender says.',
  },
  'bar:peace': {
    label: 'Make peace (buy them a bottle, 300 cr)',
    gate: 'You have made peace already tonight.',
    result: '{first} looks at the bottle a long time before taking it, turning it in the light to read the label. Then they set it between you on the table and pour two glasses. "It\'s a start," they say.',
  },
  'bar:goal-help': {
    'gift.result': 'You put it on the table and push it across.',
    'advice.result': 'You tell them what you know, plainly.',
    'listen.result': 'You sit back, and ask, and for an hour that is all there is.',
    thanks: 'As thanks {first} leans in. "Here\'s something you can use," they say: "{rumor}"',
    quiet: 'In the quiet after, {first} {slip}',
    'close.label': 'Say you hope it goes well',
    'close.result': '{first} thanks you, and that is the end of it.',
  },
  'bar:secret-help': {
    'close.label': 'Let it be',
    'close.result': 'You let it be, and the talk goes somewhere easier.',
  },
  'social:handover': {
    title: 'The Handover',
    text: '{A} is at the engine room hatch with the watch log open, and {B} is on the other side of the panel with their coat already on. "You wrote \'not done\'," {B} says. "It was not done," {A} says. "It was done at four." Somebody coming off watch turns round in the corridor and goes the long way.',
    'c0.label': 'Read the log and rule on it',
    'c0.result': 'You read the entries and the timestamps. {winner} is right, by eleven minutes. {loser} takes the log back, reads the line, and does not say anything that would go in it.',
    'c1.label': 'Split their watches so they do not meet',
    'c1.result': 'You rewrite the rota so that {A} and {B} are never on the same changeover. It works. The handovers go quiet, and the log is a little cleaner, and neither of them thanks you.',
    'c2.label': 'Make them do the handover together, standing up',
    'c2.win': 'They go through it line by line, standing at the panel. Halfway down the page {B} says the four o\'clock entry was theirs, and {A} says it was a close call. It is not warm, but it is a handover.',
    'c2.lose': 'They do the handover standing, and they do not look at each other, and when it is finished each of them writes their own initials in a different ink.',
  },
  'social:cold-shoulders': {
    title: 'Cold Shoulders',
    text: '{A} and {B} have not spoken in three days, and the ship has noticed. Messages go through {via}: "tell them the filter is changed", "tell them I heard". At dinner they sit at opposite ends of the table and the talk goes quiet, and then starts again, a little too loud.',
    'c0.label': 'Put them on the same job',
    'c0.win': 'You give them the cargo bay inventory, two of them, one list. For the first hour they count in silence. By the second hour one of them says a number out loud and the other repeats it back, and that is a start.',
    'c0.lose': 'You give them the cargo bay inventory. They finish it in half the time, by splitting the bay down the middle and not crossing the line.',
    'c1.label': 'Talk to each of them alone',
    'c1.result': 'You hear {A} out for twenty minutes over a cup of tea, then {B} for the same. Both of them leave a little lighter, and neither agrees to go first.',
    'c2.label': 'Let it run',
    'c2.result': 'You leave it. By the end of the week the messages have stopped going through {via2}, because it is quicker not to send them.',
  },
  'social:replay': {
    title: 'The Replay',
    text: '{A} ({ta}) and {B} ({tb}) have had the same argument for an hour: a famous fixture between their sides, a disputed call, a goal that stood or did not. {A} has the date. {B} has a cousin who was in the stand. The archive is one command away.',
    'c0.label': 'Play the old fixture from the archive',
    'c0.result': '{ma} {msa}, {mb} {msb}. {winner} says it is what they said all along. {loser} says the archive has the wrong referee.',
    'c1.label': 'Rule on the disputed call yourself',
    'c1.result': 'You rule that the goal stood. {winner} stands up and shakes your hand. {loser} says nobody asked you, and then asks you to say it again.',
    'c2.label': 'Mute the feed',
    'c2.result': 'You turn the sound down on the galley screen. They go on arguing for another ten minutes, with their hands, and then they go quiet and put the sound back up to watch something else.',
  },
  'social:recipe': {
    title: 'The Recipe',
    text: '{A} and {B} are in the galley, working out a dish from {home}. They disagree about the spice, the pan and the order, and agree entirely about how it should taste. There is a list on the cabinet door and a space after "chili" with a question mark.',
    'c0.label': 'Pay for the missing ingredients (150 cr)',
    'c0.result': 'You find them at the next port stall for 150 cr. The dish takes two hours and the whole ship smells of it. {A} and {B} eat theirs standing up, without talking, and then wash up together.',
    'c1.label': 'Let them make do',
    'c1.result': 'They make do. It is not the dish. They eat it and say so, and then say what the real one tastes like, for the rest of the watch.',
  },
  'social:cover-watch': {
    title: 'Cover My Watch',
    text: '{n} catches you at the end of your shift, a little too casually. "I have got the {post} watch tonight," {n} says, "and there is somebody I would like to talk to on the long link while it is still early where they are. Could you take it? I will show you what to do. It is not hard. I would owe you one."',
    'c0.label': 'Take {n}\'s watch',
    'c0.result': '{n} walks you through the board in ten minutes and goes off with a face you have not seen on them before. The watch is long, and quiet, and you learn more about the {post} post than you expected.{learn}',
    'c1.label': 'Say you have your own watch to keep',
    'c1.result': '{n} nods and says it is no trouble. They find somebody else, and you can hear, from the corridor, the second person saying yes.',
  },
  'social:ships-rules': {
    title: 'Ship\'s Rules',
    text: '{A} and {B} find you on the bridge at the end of the watch, standing a little closer together than they need to. {A} clears their throat twice. {B} studies the ceiling. Finally, in a rush, {A} says: "Captain. Does the ship have rules about crew who are, um. Together?" They both look at you. Their hands are very nearly touching.',
    'c0.label': '"No rules. Be happy."',
    'c0.result': 'They leave hand in hand, smiling at the deck. By dinner the whole ship knows, and that night someone hangs a string of fairy lights outside their berth without a word.',
    'c1.label': '"Keep it off the bridge."',
    'c1.result': '"Deal," says {A}, at once, and {B} laughs, and the two of them leave the cockpit fast. For the next few days they are very professional on the bridge, and, every so often, when they think you are not looking, one of them smiles at a console.',
    'c2.label': '"It stays professional."',
    'c2.result': 'They nod, stiffly, in unison, and thank you for your time. The ship gets a lot quieter. In the days after, they keep to opposite sides of the corridor, and {A} eats alone, and {B} stands at the viewport with an untouched mug.',
  },
  'social:close-quarters': {
    title: 'Close Quarters',
    text: '{A} and {B} keep finding reasons to share the same watch. It started as a coincidence, then a scheduling quirk, and now it is a system of trades and favors and carefully-timed sick days. They talk through the long quiet hours, in low voices, and, when someone else comes in, they both stop, and look at nothing at all.',
    'c0.label': 'Put them on the same rotation',
    'c0.result': 'You pencil them onto the same rotation, and hand over the new roster, without comment. {A} pretends not to be pleased, and studies the paper as if it were a contract. {B} does not bother pretending, and grins, and squeezes {A}\'s arm, and then examines the ceiling.',
    'c1.label': 'Leave the rotation alone',
    'c1.result': 'You leave the roster as it is, and say nothing, and, by the end of the week, they have found each other on the same watch anyway, by a route that involves three trades and a forged note. At the next meal you pretend not to notice, and everyone at the table pretends with you, at some length.',
  },
  'social:small-ship': {
    title: 'A Small Ship',
    'text.0': '{A} and {B} are on their feet in the galley. The galley is eleven feet across, and everyone who is not on watch is in it. They are arguing about {cause}. "If you\'d said something," {B} says. "I said something," {A} says. "Tuesday. Ask anyone." Nobody at the table answers.',
    'text.1': '{A} has {B} backed against the coffee dispenser. They are arguing about {cause}. "Do not tell me it\'s the principle," {B} says. "It is the principle," {A} says. Someone at the table has a spoon halfway to their mouth and has not moved it.',
    'text.2': '{A} and {B} are arguing about {cause}, standing, leaning across the table. "Say it again," {B} says. "Every day until we dock," {A} says. Someone at the end of the table says, to their plate, that it is a long way to dock.',
    'text.3': 'Third watch, the galley light on low. {A} and {B} are arguing about {cause} in whispers. The berths are behind a thin bulkhead. "Outside," {B} says. "No," {A} says. "Here. I want it witnessed."',
    'c0.label': 'Side with {A}',
    'c0.result': '"{A} has the right of it," you say. {B} looks at you, then at {A}, and leaves. The bunk door is on a pneumatic closer and does not slam; it hisses shut. "Thanks, Captain," {A} says to the table. Nobody answers.',
    'c1.label': 'Side with {B}',
    'c1.result': '"{B} has the right of it," you say. {A} looks at you, then at {B}, and leaves. The bunk door is on a pneumatic closer and does not slam; it hisses shut. "Thanks, Captain," {B} says to the table. Nobody answers.',
    'c2.label': 'Lock them in the galley until they sort it out',
    'c2.win': 'You dog the hatch from the outside and sit on the deck with your back to it. There is shouting for twenty minutes. Then there is only the air handler. Then {A} laughs, once. An hour and a half later you open the hatch. Both of them are hoarse. They are arguing about somebody\'s brother-in-law.',
    'c2.lose': 'You dog the hatch. There is shouting, then a crash, then only the air handler. Two hours later you open it, and they walk past you one at a time without speaking. A cupboard door is hanging by its top hinge ({armor} points of hull). At dinner someone sits between them with a tray. The talk is about the water ration.',
    'c3.label': 'Settle it over cards',
    'c3.result': 'The deck is in the galley drawer, under the manual for a pump the ship does not have. You deal three hands. Nobody talks. The recycler runs. {winner} takes the last hand, and {loser} washes the dishes. Over the sink {loser} goes through what is wrong with the rules, the deck, the lighting and {winner}\'s mother. {winner} drinks the last of the coffee.',
  },
  'social:small-system': {
    title: 'Small System',
    'text.home.0': '{A} and {B} are arguing about coffee at the galley table when {B} says the name of a street on {home}. {A} stops with the cup halfway up. "Which end?" {A} says. "The water end." "Then you know the baker." They were a few decks apart on {home} for twelve years and never met. The coffee goes cold. They compare teachers, bars and the {team} seasons.',
    'text.home.1': '{A} hears {B} humming in the corridor. It is a tune from {home}, a bad one, from a bar {A} knows. "That is a {home} tune," {A} says. {B} puts the filter down. "Where were you?" By the end of the watch they have named three people they both know and one they both owe money.',
    'text.culture.0': '{A} and {B} have spent the morning trading rhymes and sayings from home, fast and low, in the same slang. The rest of the crew understands one word in three. Someone asks what a word means. They both try to say, and both stop.',
    'text.culture.1': '{B} says something in the old slang at the galley table and {A} answers without thinking, in the same words. They look at each other. "My grandmother used to say that," {A} says. "So did mine," {B} says. They are still going when the watch changes.',
    'c0.label': 'Break out something to toast with (200 cr)',
    'c0.result': 'You open a bottle from the locker. They toast {where}, the old teachers, and the people who did not get out. Somebody starts a song, and the others know it. It is late when it ends. {A} and {B} go to their bunks together, not quite steady.',
    'c1.label': 'Leave them to it',
    'c1.result': 'You leave them the galley and go up to the bridge and shut the hatch. You can hear them through the deck for a long time.',
  },
  'social:grand-tour': {
    title: 'The Grand Tour',
    text: '{host} has been showing {guest} how the ship works, starting at the cargo bay and working slowly aft, with a running commentary on every valve. {visitor} The two of them keep vanishing around corners together, and reappearing, talking.',
    'c0.label': 'Let them',
    'c0.result': 'By the end of the burn {guest} can name every valve on the ship, and knows which pipe rattles in which key, and has, in a small notebook, a hand-drawn diagram of the whole drive. At the end of the last watch {host} catches your eye across the galley, and nods once.',
    'c1.label': 'Passengers stay out of the engine room',
    'c1.result': 'Rules are rules, and you say so, gently. {host} nods, without protest, and steers {guest} back to the galley, and the tour ends mid-sentence. For the rest of the burn, {guest} keeps glancing at the engine room hatch, and {host} does not look at you.',
    'visitor.nervous': '{guest} jumps at every clank, and holds a handrail with both hands, and, every so often, asks a careful question.',
    'visitor.keen': '{guest} has a hundred questions, and asks all of them, at speed, and, at each answer, nods and writes something down.',
  },
  'social:word': {
    'c0.label': '"Talk to {B}, not me."',
    'c1.hired.label': '"That is between the two of you."',
    'c1.hired.result': '{A} nods, and says, "Right. Sorry," and goes. An hour later you hear them ask the cook the same question, in a lower voice.',
    'c1.label': '"Keep your head down and do your job."',
    'c1.result': '{A} nods, and says, "Aye, captain," and goes. For a while, {A} is brisk and correct, and answers in single words.',
    'c2.label': '"What\'s {B} really like?"',
    title: 'A Word, Captain',
    'title.hired': 'A Word',
    'text.hired': '{A} catches you alone, by the lockers while you are stowing your kit, one shoulder against the bulkhead. "Hey. Can I ask you something about {B}?" {mood} They wait, and watch your face, and their hands, at their sides, are very still.',
    text: '{A} catches you alone, in the corridor outside the cockpit, one shoulder against the bulkhead. "Captain. Can I ask you something about {B}?" {mood} They wait, and watch your face, and their hands, at their sides, are very still.',
    'mood.warm': 'Their voice is casual, and their ears have gone pink.',
    'mood.tight': 'Their voice is level, and tight at the edges.',
    'c0.warm': '{A} takes a deep breath, and nods, and goes, and, later, you see the two of them in the galley, heads close together, talking quietly, over two untouched cups of tea. Good. When they notice you, they both look up, and neither looks away.',
    'c0.tight': '{A} takes a deep breath, and nods, and goes. They do. It is loud for a while, behind a closed door, and then it is quieter. When they come out, both are red-eyed, and neither is leaving.',
    'c2.result': '"{B}? {trait}Watches too much {genre}. Would go down with the ship for you, though." {A} stops, and blinks, and looks at the deck. "Anyway," they say. "That is what {B} is like."',
  },
  'social:galley-duty': {
    title: 'Galley Duty',
    'text.0': 'The galley rota is a sheet taped to the cabinet door. {A} has written {B}\'s name on every day of next week, and {B} has written {A}\'s name over it. {A} backs {ta}. {B} backs {tb}. Whoever\'s team loses tonight does the dishes. Both of them have initialed it.',
    'text.1': '"A week," {B} says. "Dishes, filters, the lot." "Done," {A} says, and they shake on it across the table. {A} has {ta}. {B} has {tb}. The match is tonight.',
    'text.2': '{A} ({ta}) and {B} ({tb}) have put the galley rota on the match. The loser takes all of it for a week. It is written on the cabinet door in {A}\'s handwriting. {B} has added "and no complaints" and underlined it twice.',
    'text.3': 'The ship\'s feed has {ta} against {tb} at the end of watch. {A} and {B} have turned the chairs to face the screen. A week of galley duty, loser\'s. They have not spoken since they agreed it.',
    'c0.label': 'Stream it for everyone',
    'c1.label': 'Put 300 cr on the {ta} yourself',
    'c2.label': 'Stay out of it',
    'c2.result': 'You hear the result through the bulkhead: cheering, then a groan, then someone banging a pan.',
    'c0.rude': '{loser} does the week of galley duty. Every pan goes into the rack hard, and for four days {loser} goes through what the referee did.',
    'c0.easy': '{loser} does the week of galley duty in an apron two sizes too small, and does not mention the score.',
    'c1.win': 'You collect 300 cr. {A} wants to buy a round with it.',
    'c1.lose': 'You lose 300 cr. {B} brings it up at every meal until the next match.',
  },
  'social:welcome-back': {
    title: 'Welcome Back',
    text: '{first} {last} settles into the same berth as last time.',
    'text.memory': '"Last time, {memory}"',
    'text.friends': '{names} have saved them the good mug.',
    'text.friend': '{names} has saved them the good mug.',
    'c0.label': '"Good to have you aboard again."',
    'c0.result': '{first} grins and goes straight for the good mug.',
  },
  'social:feed': {
    'most-watched': '"{title}" is the most-watched {genre} on the Mars feeds this week.',
    critics: 'Critics on Luna call "{title}" {verdict}.',
    cliffhanger: 'Episode {ep} of "{title}" ends on a cliffhanger. Half the Belt is furious.',
    'book-tops': '"{book}" by {author} tops the reading lists again.',
    'book-denies': '{author} denies that "{book}" is about a real Compact admiral.',
    'song-playlist': '"{song}" by {band} is on every station playlist from Mercury to Titan.',
    'band-cancels': '{band} cancel their Ceres concert, citing "water ration reasons".',
    'star-spotted': '{s1}, star of "{title}", was spotted on {place} with {s2}. Nobody is confirming anything.',
    'star-walkout': '{s1} walked off the set of "{title}" after a fight about the lighting.',
    'stars-feud': '{s2} and {s1} are feuding on the feeds again. It is the best thing on.',
    'script-leak': 'A leaked script says {s1}\'s character dies in the "{title}" finale.',
    interview: '{s2} gives a two-hour interview about "{title}" and does not mention {s1} once. The comments are on fire.',
    petition: 'Fans of "{title}" on Ceres have started a petition to bring back a character nobody remembers. It has four hundred thousand signatures.',
    bootleg: 'A bootleg cut of "{title}" is doing the rounds on the Belt stations, with a much better ending and a much worse soundtrack.',
    sequel: '{author} announces a sequel to "{book}", and a small riot breaks out in a bookshop on Luna.',
    podcast: 'Somebody on Mars has started a podcast that only discusses one chapter of "{book}", and it is somehow already on its ninth season.',
    'surprise-show': '{band} play a surprise show at a smelter on Pallas, and the crowd sings every word back. The refinery has the footage.',
    cover: 'A cover of "{song}" sung by a hauler crew in the ice lanes is quietly going around, and it is, by any measure, better than the original.',
    'water-price': 'The feeds report that the water price on Ceres has become, once more, the only story anyone wants to talk about.',
    comedian: 'An old Belt comedian retires, after fifty years, with a last show that ends with a joke about recyclers. Every station stops to watch.',
    'ring-ball-kid': 'A kid on Ganymede beats the record for most consecutive ring-ball goals, and the entire agri-dome has declared a holiday.',
    'press-office': 'Somebody in the Compact\'s press office accidentally posts the wrong file, and spends an afternoon being the most-quoted person in the system.',
    'food-craze': 'A new food craze sweeps the outer stations: it is noodles, again, but this time with, of all things, cheese.',
    rain: 'Weather on Earth: rain for the ninth day running. The feeds, by popular demand, have started a rain channel, and it is astonishingly popular in the Belt.',
    documentary: 'A long, gentle documentary about the ice haulers of Europa is being watched on every ship in the outer system. It has no plot. People are crying anyway.',
    premiere: '"{title}" premieres this week, and the feeds are already calling it the show of the year.',
    finale: 'The finale of "{title}" is on this week. Half the system has cleared its schedule.',
    broadcast: 'Tonight on every feed: "{title}". {blurb}',
    'league.preseason': 'The {league} is back in a few weeks, and the {team} have signed a new striker, or so they say.',
    'league.playoffs': '{league} playoffs: the {teams} are through, and everyone else is pretending to be fine.',
    'league.final': 'It is the {league} final tonight, {teams}. Every bar from here to Titan is full.',
    'league.result': '{Sport}: {ta} {sa}, {tb} {sb}.',
    'league.leaders': 'The {leader} lead the {league} with {wins} wins.',
    'league.champs': 'The {champ} are still celebrating their {league} title, and the other fans are sick of it.',
    war: 'War dramas are all anyone in {wa} space watches now, and the {wb} feeds are no better.',
    gossip: 'Dock gossip from {place}: {first} {last} is still telling anyone who listens, "{mem}"',
  },
  'social:crew-talk': {
    lost: '{n} does not want to talk about the {team} game.',
    read: '{n} is halfway through "{title}" and keeps reading bits aloud.',
    song: 'Someone has had "{song}" stuck in their head since the last port, and now so does everyone.',
    humming: '{who} is humming the theme from "{title}" in the corridor, and does not know they are doing it.',
    table: 'The galley wall now has a hand-lettered ring-ball league table, and it is being updated with a great deal of feeling.',
    debate: 'There is a heated, low-voiced debate in the galley about whether "{book}" is better than the vid. It has been going on since breakfast.',
    tea: 'Somebody has left a mug of cold tea on every flat surface in the ship, and nobody will admit to it.',
    bunks: '{A} and {B} have pushed their bunks together. Nobody says anything.',
    coffee: '{A} saved {B} the last of the good coffee.',
    laughing: '{A} and {B} are laughing at something on {A}\'s terminal.',
    teaching: '{A} is teaching {B} a card game from {home}.',
    'not-speaking': '{A} and {B} are not speaking. It is a small ship.',
    rations: '{A} ate {B}\'s labeled rations. On purpose, according to {B}.',
    won: '{n}: "{team}, {hi} to {lo}!{pay}"',
    'won.pay': 'Pay up, {rival}.',
    'fav.finale': '{n} is dreading the finale of "{title}" in their bunk.',
    fav: '{n} is rewatching "{title}" in their bunk. Again.',
  },
  'social:headlines': {
    broadcast: 'Tonight only: "{title}".',
    reading: 'Reading: "{title}" by {author}.',
    listening: 'Listening: "{song}" by {band}.',
    'watching.premiere': 'Watching: "{title}", a {genre}, the premiere.',
    'watching.finale': 'Watching: "{title}", a {genre}, the finale.',
    watching: 'Watching: "{title}", a {genre}, episode {ep} of {eps}.',
    league: '{league}: {status}',
    'league.champs': 'the {champ} are champions.',
    'league.off': 'off-season.',
    'league.pre': 'preseason.',
    'league.last': '{ta} {sa}, {tb} {sb}.',
    'league.final': 'The final is tonight.',
    'league.playoffs': 'Playoffs: {teams}.',
    'league.lead': 'The {leader} lead with {wins} wins.',
    'league.start': 'The season has just started.',
  },
  'social:card-night': {
    label: 'Card night',
    win: 'You clean everyone out for {won} cr. {who} swears the deck is marked. It isn\'t. Probably.',
    lose: '{who} takes the pot, and {lost} cr of yours with it. Over the last hand you hear the ship\'s gossip{tail}',
    'lose.gossip': ': {gossip}',
    'lose.nogossip': ', which is mostly about you.',
  },
  'social:watch-show': {
    nofans: 'Nobody is a fan.',
    bored: '{who} falls asleep before the first act break.',
    feud: '{A} and {B} argue about the ending for an hour, which is almost friendly.',
    label: 'Watch "{title}", {when}',
    'when.premiere': 'the premiere',
    'when.finale': 'the finale',
    when: 'episode {ep}',
    intro: 'You crowd into the galley for {when} of "{title}", a {genre}.',
    fans: '{names} know every line.',
    fan: '{names} knows every line.',
  },
  'social:read-book': {
    label: 'Pass around "{title}"',
    intro: 'The ship\'s one printed copy of "{title}" by {author} does the rounds.',
    bored: '{who} leaves pointed notes in the margins.',
    club: 'By the end of the burn there is a book club, and it has opinions.',
    fans: '{names} fight over who reads it next.',
    fan: '{names} reads it twice.',
  },
  'social:watch-broadcast': {
    label: 'Watch "{title}", tonight only',
    intro: 'Everyone crowds into the galley for "{title}". {blurb}',
    nofans: 'Nobody aboard is a fan, but nobody leaves, either.',
    bored: '{who} complains the whole way through, and stays to the end.',
    fans: '{names} were not going to miss it for anything.',
    fan: '{names} was not going to miss it for anything.',
  },
  'social:stream-match': {
    intro: 'The lagged stream from {place} comes in: {ma} against {mb}, {sport}. Final score {sa} to {sb}.',
    nobody: 'Nobody aboard cares who wins, so everyone picks a side for the fun of it.',
    label: 'Stream the {league} {kind}',
    'kind.final': 'final',
    'kind.playoffs': 'playoffs',
    kind: 'match',
    'won.many': '{names} are unbearable for the rest of the day.',
    won: '{names} is unbearable for the rest of the day.',
    'lost.badly.many': '{names} take it badly.',
    'lost.badly': '{names} takes it badly.',
    'lost.grace.many': '{names} take it with some grace.',
    'lost.grace': '{names} takes it with some grace.',
  },
  // The "With {name}" scenes of js/family.js (#457): the talk topics, the idle talk, the sittings of a story, the favor and the picker.
  'family:mood': {
    title: 'With {n}',
    'open.news': '{n} is quiet, and has been since the news: {news}. A mug sits in front of them, untouched.',
    'open.plain': '{n} is quiet, and has been since the last message from home. A mug sits in front of them, untouched.',
    'c0.label': 'Let them talk',
    'c0.result': 'You say nothing, and {n} talks, in pieces, about {missed}, and what they cannot do from here. By the end the mug is empty. They set the empty mug in the rack and say, to the rack, that it was a long watch.',
    'c1.label': 'Offer to take a watch off them',
    'c1.result': '{n} starts to say no, and then does not. "Just the one," {n} says. A corner of their mouth goes up.',
    'c2.label': '"It will pass."',
    'c2.result': '{n} nods. "It does," they say. "It just takes its time." You both drink your coffee.',
  },
  'family:hurt': {
    title: 'With {n}',
    open: '{n} is favoring one side, and has been all watch. They have not asked for anything, and they have not sat down properly in two days.',
    'c0.label': 'Ask how it is',
    'c0.result': '"It is fine," {n} says, and then, when you wait, "It is not fine. It is getting better." You nod. {n} lowers themselves onto the bench, bad side last.',
    'c1.label': 'Tell them to rest',
    'c1.result': '{n} argues for a minute and then goes to their bunk. You can hear them let out a long breath through the bulkhead.',
  },
  'family:war': {
    title: 'With {n}',
    open: '{n} has had the war on the galley screen since it started, the {aff} against the {foe}, with the sound off. "Do not tell me it will be over soon," {n} says.',
    'c0.label': 'Ask what they think',
    'c0.result': '{n} thinks about it for a while. "I think I would have stayed home," {n} says, "and I think I would have been wrong." You do not have anything to add to that.',
    'c1.label': 'Ask if they want to go home',
    'c1.result': '"Every day," {n} says. "And then I look at what is on the screen and I think, not like this."',
    'c2.label': 'Change the subject',
    'c2.result': 'You ask about the food at the last port. {n} is grateful for that, and says so by going on about it for ten minutes.',
  },
  'family:rift': {
    title: 'With {n}',
    open: '{n} is short with {other} all through the meal, and then pretends not to be.',
    'c0.label': 'Ask what happened',
    'c0.result': '{n} says it was nothing, and then says it was the thing at the rota, and then the thing from before. "I do not even like being angry," {n} says. "It is just there."',
    'c1.label': 'Stay out of it',
    'c1.result': 'You say you will not take sides. {n} nods, a little disappointed, and you finish the coffee talking about something else.',
  },
  'family:friend': {
    title: 'With {n}',
    open: '{n} laughs at something {other} said across the galley, and then catches you looking. "We have been through a lot," {n} says, a little defensively.',
    'c0.label': 'Ask about {other}',
    'c0.result': '{n} talks about {other} for a long time: how they met, what {other} is like on a bad day, the one thing {n} would never say to their face. It is the warmest part of the watch.',
    'c1.label': 'Say you can tell',
    'c1.result': '"You can tell?" {n} says. They glance past you at the corridor. "Do not say anything." You will not.',
  },
  'family:memory': {
    title: 'With {n}',
    open: '{n} says, without quite looking at you, that they have been thinking about something: "{mem}"',
    'c0.label': 'Bring it up',
    'c0.result': 'You say you remember it too. {n} looks up. "I did not think you would," {n} says. It is quiet for a moment, and then it is easy.',
    'c1.label': 'Let it lie',
    'c1.result': 'You let it lie. {n} nods, and after a minute the talk turns to the next port, and you both pretend that was the point.',
  },
  'family:idle': {
    title: 'With {n}',
    text: 'You sit with {n} in the galley, over two mugs. {n} {idle}. The drive hums. A pipe ticks.',
    easy: 'is easy company',
    'c0.label': 'Stay a while',
    'c0.result.0': 'The ship hums around you both, steady and warm. Somewhere aft, a door closes. You watch {n}\'s shoulders come down, one careful inch at a time.',
    'c0.result.1': 'You do not say much, and neither does {n}. When you stand to go, {n} says it was good, and the mug is still warm in your hand.',
    'c0.result.2': '{n} tells you a story about the last ship they were on. It is a small one, and it goes nowhere, and when it ends you both look into your mugs.',
    'c1.label': 'Ask {n} about {home}',
    'c1.result': '{n} tells you what they miss about {home}, and what they do not. By the end it is hard to say which list is longer.',
  },
  'family:polite': {
    title: 'With {n}',
    text: 'You sit with {n} in the galley for a while, over two mugs going cold. They talk about the ship, the food, the noise the recycler makes at night, the next port. It is easy and polite. Whenever the talk drifts toward anything real, {n} asks about the food, or the next port, or whether you have eaten. Nothing about themselves, not yet.',
    'c0.label': 'That\'s all right',
    'c0.result': 'You let it be, and finish your coffee, and say nothing about the hole in the floor. Some people take longer, and that is all right too. When you get up to go, {n} looks up quickly and says, "Thanks for the company." It is more than they have said all week.',
  },
  'family:story-home': {
    title: 'With {n}',
    text: '{n} tells you about {home}: {detail}. They turn their mug a quarter turn on the table as they say it. Then, unprompted, they say they left because of {left}, and stop, and drink, and look at you.',
    'c0.label': 'Listen',
    'c0.result.0': 'You say nothing, and let the silence hold, and {n} goes on about smaller things: a street, a smell, a name. It is a long while before either of you looks at the clock. At the end {n} says it is late, and does not get up.',
    'c0.result.1': '{n} talks for most of an hour, and you mostly listen, and, when they run down, they let out a long breath. "I never told anyone that," they say, quietly. "Not aloud."',
    'c1.label': 'Tell them about where you came from',
    'c1.result': 'You tell them something true and small about where you came from, and {n} listens with their whole face, laughs, and at one point reaches over and steals a bite off your plate. "Everybody out here is from somewhere they left," they say. "It is a little bit of a comfort."',
  },
  'family:story-picture': {
    title: 'With {n}',
    text: '{n} takes something out of a breast pocket, a small worn picture, soft at the edges from handling, and slides it across the table. It shows their {missed}, squinting into the light, mid-laugh. "We used to talk every day," {n} says. "Now it is a message every few weeks, with a lag. Half of what I say is out of date before they hear it." They look at the picture for a while. Then they put it back in the pocket and button the flap.',
    'c0.label': '"Tell me about them."',
    'c0.result': '{n} does, and it takes a long time, and it is not a story so much as a list of small things: how their {rel} hums when they cook, what they say when they lose at cards, the particular way they pronounce the name of a place. By the end, {n} is smiling, and there are tears in it, and neither of you mentions them.',
    'c1.label': '"You\'ll see them again."',
    'c1.result': '{n} looks at you for a moment. "You cannot promise that," they say. They take the picture out again and prop it against the sugar tin. "No," they say. "But thank you for saying it."',
  },
  'family:story-hope': {
    title: 'With {n}',
    text: 'Late in the watch, when the corridors are dim and the ship is quiet, {n} admits what they really want: {hope}. They say it in a rush, looking at their hands, and as soon as it is out they laugh, a short laugh that asks you not to laugh with them. Then they go still, and wait, with their shoulders braced.',
    'c0.label': '"It\'s not a stupid thing to want."',
    'c0.result': 'You tell them, plainly, that it is not, and {n} lets out a long, slow breath. "Nobody has ever said that to me," they say. "They say it is nice, or it is late. They never say it is not stupid." They are quiet for a bit. "I think I needed someone to just say it."',
    'c1.label': '"If I can help, I will."',
    'c1.result': 'You say it simply, and {n} looks up. "You mean that," they say. Then: "I am going to remember you said it." They refill your mug without being asked.',
  },
  'family:favor-visit': {
    title: 'A Favor',
    text: '{n} comes to find you in the cockpit, and stands in the hatch, twisting the hem of their sleeve, which is not like them. "Could we put in at {home} sometime?" they ask. "I want to see my {missed} while I still can. It has been too long. I would work the whole trip for nothing, captain, I swear, I would work double, just to see them one time." They stop. Their voice has gone thin. "I have never asked for anything before."',
    'c0.label': '"We\'ll go."',
    'c0.result': '{n} does not say anything. For a moment, you are afraid they will cry. Instead, they put a hand on the back of your seat, and squeeze, once, hard, and go out. That night the whole ship smells of something baking, and nobody says why. (It\'s on your missions list.)',
    'c1.label': '"Not yet. But soon."',
    'c1.result': '{n} nods. "Soon, then," they say. "I can wait. I have gotten good at it." They do not bring it up again.',
  },
  'family:favor-debt': {
    title: 'A Favor',
    text: '{n} finds you alone, at the end of the watch, and sits down without being asked, hands flat on the table. "I owe {debt} cr to people on {home}," they say, all in one breath. "It is the real reason I left. They send messages. I do not open them anymore. I just watch the little number go up." They look at you, at last, and do not look away. "I am not asking. I just wanted you to know, before you decide whether I am worth what you pay me."',
    'c0.label': 'Pay it off ({debt} cr)',
    'c0.result': '{n} reads the confirmation three times, with their lips moving, and puts the screen face-down on the table, and goes to their bunk. After a while you hear them crying through the bulkhead, and, after a longer while, laughing. In the morning they are making everyone breakfast. They will not look you in the eye, and they will not stop smiling.',
    'c1.label': '"I can\'t, not now."',
    'c1.result': '"I know," {n} says. "I did not expect you to." They stand, touch the table once, and go back to work.',
  },
  'family:picker': {
    title: 'Sit With Someone',
    'text.0': 'You make two mugs of coffee. Who could use the company?',
    'text.1': 'The galley is empty, and the kettle has just clicked off. Somebody aboard might like a cup.',
    'text.2': 'Between watches, you find yourself with an hour and two mugs. Who gets the second one?',
    'text.3': 'The ship is quiet tonight. You could use the company yourself, and so, maybe, could someone else.',
    'text.4': 'You are carrying a plate of the good biscuits down the corridor. Who is it for?',
    go: 'You find {first} in the galley.',
  },
  // The rest of the found-family scenes of js/family.js (#457): the birthday and the holidays, the letters' scenes, the traditions, the cat and the offer to stay.
  'family:birthday': {
    title: '{n}\'s Birthday',
    text: 'It is {date}, and it is {n}\'s birthday. {act}',
    'act.0': '{n} hasn\'t mentioned it. All week, {n} has been somewhere near the galley whenever anyone is in it.',
    'act.1': '{n} mentioned it once, weeks ago, in passing. At every meal since, {n} has been busy with something on the far side of the galley.',
    'act.2': '{n} says birthdays are for dirtsiders. They have said it twice this morning, too loudly, and have, for some reason, put on their good jacket.',
    'act.3': '{n} woke up early, and cleaned the galley, and is now sitting straight at the table, with a clean mug set out at every place.',
    'c0.label': 'Throw a party in the galley',
    'c0.result': 'Somebody makes a cake out of ration bars and a candle out of a welding stub, and somebody else finds a bottle no one admits to hiding. The whole ship crowds into the galley to sing, off-key and enthusiastically, and {n}, who was going to be cool about it, laughs until they cry, and blows out the welding stub on the third try.',
    'c1.label': 'Give them something from the cargo (1t luxury goods)',
    'c1.gate': 'There is no luxury cargo in the hold.',
    'c1.result': '{n} unwraps it slowly, saving the paper. When they see what it is, they go still. They do not say anything for a moment. Then they set it on the shelf by their bunk, and keep it there for the rest of the trip. More than once you see them stop and look at it.',
    'c2.label': 'A quiet word and a drink',
    'c2.result': 'You find {n} alone in the galley, and set down two cups, and say the words, plainly. "You remembered," they say, and look at the cup. You sit together and drink and say little.',
  },
  'family:holiday': {  // the words of each holiday are in the table lines:family-holidays; these are the choices every holiday has
    'c0.label': 'Everyone joins in',
    'c1.label': 'Let {n} mark it their own way',
    'c1.result': '{n} nods, and thanks you, and marks it alone in their bunk, with the curtain drawn. You hear music through the bulkhead, something old, from home, and, once, a laugh. In the morning they are cheerful, and nobody asks.',
  },
  'family:news-good': {
    title: 'Good News',
    'open.0': '{n} comes into the galley fast, holding the terminal out in front of them. "Listen," {n} says. "Listen to this." The message reads: {news}. {n} reads it aloud, loses their place, and starts again.',
    'open.1': '{n} stops you at the hatch. "Captain. Listen to this." The message is open on the terminal: {news}. {n} reads it aloud twice. The second time, {n} has to stop partway through.',
    'open.2': 'You find {n} in the corridor with the terminal pressed flat against their chest and their eyes shut. Then they hold it out to you: {news}. "I had to tell somebody," {n} says. "You were closest."',
    'open.3': '{n} has been humming since the start of watch. You ask why, and {n} hands you the terminal: {news}. {n} stands there while you read it.',
    'open.4': '{n} slides the terminal across the galley table without a word and watches you read it. The message: {news}. "Third time I have read it," {n} says. "It still says that."',
    'open.5': 'Over the intercom, {n}: "Captain, can you come aft? It is not an emergency." You find {n} at the engine room hatch with the terminal. The message: {news}. {n} is grinning at the deck.',
    'open.6': 'The message came in at the last port, and {n} carried it for a watch before saying anything. At the galley table {n} says it: {news}. Somebody at the table drops a spoon.',
    'open.7': '{n} is waiting for you at the end of the watch, rocking on their heels. "Captain, do you have a minute?" The terminal is already out: {news}. "That is all," {n} says. "That is the whole thing."',
    'c0.label': 'Break out something to celebrate',
    'c0.result.0': 'You break out the good bottle. Within the hour everyone who is not on watch is in the galley, and everyone has a toast. Someone finds the guitar, which has two strings. It goes past midnight. Nobody mentions the watch bill.',
    'c0.result.1': 'You open the locker and put out whatever the ship has. Cards come out, and the cook brings tomorrow\'s noodles forward a day. {n} tells the story three times, and the story changes each time. The galley is full until the watch bell.',
    'c0.result.2': 'You call the galley to order with a spoon on a pot. Everyone off watch comes. The cook finds a cake mix at the back of the cupboard and makes it in the pressure pan. It comes out flat. It is eaten.',
    'c1.label': '"That\'s wonderful."',
    'c1.result.0': '{n} shows you the picture. A minute later {n} shows you again. "I keep wanting to tell someone," {n} says, and laughs.',
    'c1.result.1': '"Tell me all of it," you say, and {n} does, from the start, with the dates. At the end {n} goes back to the part about the street and tells that again.',
    'c1.result.2': 'You read it over {n}\'s shoulder. "Send them something," you say. {n} sends a line from the bridge console and watches the relay clock for the next hour.',
  },
  'family:news-bad': {
    title: 'Bad News',
    'open.0': '{n} has been quiet since the last port. {n} stands the watch and eats, and twice has stopped with the fork halfway up. A message came in at the last port: {news}. {n} has told no one. You saw the screen over their shoulder in the corridor.',
    'open.1': '{n} missed the start of the watch briefing. You find {n} on a crate in the cargo bay with the terminal dark in their lap. The last message on it reads: {news}.',
    'open.2': '{n} has not touched their plate. Nobody at the galley table has said anything. The message is on the terminal by {n}\'s elbow: {news}.',
    'open.3': '{n} does the whole shift without a word and checks every gauge twice. Late, in the corridor, {n} tells you: {news}. "I\'m fine," {n} says.',
    'open.4': '{n} asks to speak to you in the cargo bay, where the hull carries the noise. {n} says it flat, without the terminal: {news}. "I do not need anything," {n} says. "I wanted you to know why I am slow."',
    'open.5': 'The terminal pings in the galley and {n} reads it standing, then sits down. The message: {news}. {n} finishes the coffee. Nobody at the table asks.',
    'open.6': '{n} has been at the comms station for an hour, sending messages and waiting out the lag. When you come in, {n} turns the screen toward you: {news}.',
    'open.7': 'You find {n}\'s tool roll closed on the bench, which it never is. {n} is in the corridor with the terminal. {n} says: {news}. "I will be on my watch," {n} says.',
    'sit.label': 'Sit with them',
    'sit.result.0': 'You do not fix anything. You stay in the galley with a pot of tea going cold while {n} looks at the wall. After a time {n} starts talking, low, about the person and the place and the years. When they get up, they touch your shoulder on the way out.',
    'sit.result.1': 'You bring two cups to the cargo bay and sit on a crate. {n} does not talk for a while. When {n} does, it is about the street they grew up on and a night in the market. You stay until the watch bell, and {n} says thank you at the hatch.',
    'sit.result.2': 'You sit on the other side of the galley table and do not look at the terminal. {n} tells you what the section was like before the cuts. It takes an hour. At the end {n} washes both cups.',
    'advance.label': 'Advance them 500 cr to send home',
    'advance.result.0': '{n} sends it at the next relay with a short message. For two days {n} checks the terminal every few minutes. When the reply comes, {n} reads it aloud in the galley. "They are all right," {n} says. "They are all right." They sit down.',
    'advance.result.1': '{n} sends it from the bridge console with two lines. The reply is nine hours behind the question. When it comes, {n} reads it standing at the console and says nothing until the end. "They are all right," {n} says. The next watch {n} is early.',
    'advance.result.2': '{n} will not take it at first. Then {n} says it comes out of the pay, all of it, and sends it with the evening relay. Two days later the reply comes. {n} reads it twice in the galley and puts the terminal in a pocket. They stay for dinner.',
    'ask.label': 'Ask {other} to look in on them',
    'ask.result.0': '{other} takes {n} a mug of something hot and sits down beside them on the crate by the galley wall. {other} does not speak. They are still there two hours later. Through the hatch you see two heads close together. Once, {n}\'s shoulders shake.',
    'ask.result.1': '{other} finds {n} in the cargo bay, sits down on the next crate, opens a ration bar and hands half across. They eat without talking. At the watch bell they go forward together.',
    'ask.result.2': '{other} takes {n}\'s next hour at the console without being asked. {n} sits with the terminal on their knees and does not look at it. When {other} comes back for the cup, {n} says something, and {other} nods.',
    'space.label': 'Give them space',
    'space.result.0': '{n} goes to their bunk. You hear the terminal, faintly, and later nothing. Their work suffers for a time: a missed step, a cold cup. (Their skill counts one lower until they feel better.)',
    'space.result.1': '{n} takes the cargo bay for the rest of the watch and does the manifest twice. You leave the door open. A missed step shows up in the log the next day, and {n} corrects it before anyone asks. (Their skill counts one lower until they feel better.)',
  },
  'family:tradition': {  // the name of each tradition is in code; its proposal and the line it gives in a burn are here
    title: 'A New Tradition',
    'c0.label': 'Make it a tradition',
    'c0.result': 'You say the words, and nobody speaks for a second, and then somebody laughs, and it is done. It sticks. From now on, {name} is part of life aboard {ship}.',
    'c1.label': 'Just this once',
    'c1.result': 'You say yes to the moment and no to the promise. Nobody makes a fuss, and the cups go round again.',
    'flip-toast.propose': '{n} raises a bulb of something strong as the ship turns end over end, and the stars wheel silently past the viewport, and says, in a clear voice: "To the flip. Halfway to somewhere." Everyone in the room looks at you.',
    'flip-toast.line.0': '[Ship] The flip toast: "Halfway to somewhere." Everyone drinks.',
    'flip-toast.line.1': '[Ship] At the flip, cups go up all through the ship, and a quiet, ragged chorus: "Halfway to somewhere."',
    'flip-toast.line.2': '[Ship] The flip comes, and the ship turns, and someone raises a bulb: "Halfway to somewhere." Nobody says no.',
    'first-meal.propose': '{n} cooks for everyone on the first night out, a huge, clattering pot of noodles and broth and chili, with the lid steaming and a small paper bag of scallions torn open on the counter. They ladle it out with a wooden spoon, one bowl at a time, without a word. When the last bowl is full they look around the table and say: "Tradition. Starting now."',
    'first-meal.line.0': '[Ship] First night out, and the galley smells of noodles. Tradition.',
    'first-meal.line.1': '[Ship] The first-night noodles are on, and the whole ship is queuing with bowls, in a cheerful, hungry line.',
    'first-meal.line.2': '[Ship] Noodles again, first night out. Somebody says it wouldn\'t feel like a burn without them.',
    'burn-name.propose': '{n} says every burn deserves a name, in the way that every storm deserves a name, and, ideally, every mistake. They have a marker, and a large sheet of paper taped to the galley wall. They write, in tall block letters, and propose calling this one "{b}".',
    'burn-name.line': '[Ship] By unanimous vote, this burn is called "{b}".',
    'docking-song.propose': '{n} starts singing an old work song from {home} on final approach, softly at first, mostly to themselves, a slow, rolling tune about hauling, and home, and the long way round. By the second verse, someone is harmonizing, and by the third, half the ship has joined in, off-key and untroubled, and somebody is keeping time on a pipe with a wrench.',
    'docking-song.line.0': '[Ship] Final approach, and everyone is singing the docking song, badly and with feeling.',
    'docking-song.line.1': '[Ship] The docking song starts up in the galley, and spreads through the ship, verse by verse, like weather.',
    'docking-song.line.2': '[Ship] Somebody starts the docking song, and, in the cockpit, the pilot, who swore he would not, is humming along.',
  },
  'family:cat': {
    title: 'Stowaway',
    text: 'There is a cat in the cargo lock: skinny, gray, one torn ear, a kinked tail, and completely unimpressed by you. It is sitting on the top of a crate, washing one paw, with the air of a small, ancient, extremely tired landlord. When you open the inner hatch it looks up, unhurried, and gives you a long, level stare, and goes back to its paw.',
    'name.label': '"{name}," suggests {voter}',
    'name.result': '{name} it is. The cat, for its part, does not acknowledge the name, or the vote, or the existence of the arrangement. By the time you take off, {name} has found the warmest spot on the ship, which is on the reactor housing, and has curled into a perfect gray circle, one ear twitching. Somebody puts a saucer of milk down, and somebody else makes a small bed out of a folded jacket.',
    'dock.label': 'Put it back on the dock',
    'dock.result': 'You carry it back down the ramp, in both hands, and set it on the dock, and it gives you a look you will remember for a long time, a long, level, wholly unsurprised stare, and walks off, with its tail high. Nobody on the crew speaks to you for an hour. Somewhere, in the distance, a small, imperious meow.',
  },
  'family:join': {
    title: 'One More Berth',
    text: 'The trip is over, and the other passengers have gone ashore, but {first} {last} lingers at the airlock with their bag, a battered, over-stuffed thing that has, over the burn, become oddly familiar. They shift it from hand to hand. They look at the deck, and at the hatch, and at you, and back at the deck. "I\'ve been thinking," they say at last, in a rush. "I don\'t really have anywhere I need to be. And I like it here. I like all of you. Could {ship} use a {role}?" They hold your eye and wait.',
    'c0.label': 'Welcome aboard',
    'c0.result': '{first} lets out a breath so long it is almost a laugh, and drops their bag in the same bunk as before, with a thump. "Same one," they say. "It\'s lucky." Somebody, in the galley, starts to clap. (They join as your {role}.)',
    'c1.label': '"Not this time."',
    'c1.result': '"I understand," {first} says, quickly. "Really. If you ever need someone..." They write their contact code on the back of your hand, in pen, since they do not seem to have paper, wave, shoulder their bag, and go down the ramp. You watch them all the way to the end of the dock, and, at the corner, they turn, and lift a hand, and are gone.',
  },
};
